### ISSUE TITLE
Analyzer redownloads its files on startup

### ISSUE THREAD

**Issue by ScienceKit** [SkEditorPlus/SkAnalyzer#3]
So im on windows 11 and on a fresh install of the editor and analyser it downloads missing files, which is normal.
But every time i restart the editor, the analyser redownloads its files. I guess that the file validation is broken. Could be my pc or something.

**Comment by NotroDev** [comment]
Try to delete Analyzer folder from `%appdata%/SkEditor` and Analyzer addon from Addons folder, then try to install Analyzer from the Marketplace again

**Comment by ScienceKit** [comment]
so this one goes:
![image](https://github.com/SkEditorTeam/SkAnalyzer/assets/127025473/d608758d-0a16-494b-a2b8-6f168269863a)
and this one too:
![image](https://github.com/SkEditorTeam/SkAnalyzer/assets/127025473/bf5a96ec-11e7-4d91-b256-22115b9fb1d8)

it still does the redownloading thing...

**Comment by NotroDev** [comment]
That's weird...
as a workaround, you can change AnalyzerDeveloperMode or something like this in `settings.json` file to `true`

**Comment by NotroDev** [comment]
Sorry for the wait, the issue should be fixed now, the jar's file in the code hash was incorrect, so it was detecting it as outdated
