### ISSUE TITLE
how to update script version

### ISSUE THREAD

**Issue by SzynkaDev** [SkEditorPlus/SkAnalyzer#4]
how to update this version
![Zrzut ekranu 2024-03-02 102508](https://github.com/SkEditorTeam/SkAnalyzer/assets/154932206/41a31784-9395-4785-991f-ccd068197192)

@GliczDev

**Comment by GliczDev** [comment]
You can compile dev branch version if you want to use Skript 2.8.2

**Comment by BANKAYT** [comment]
how

**Comment by SzynkaDev** [comment]
how @GliczDev

**Comment by GliczDev** [comment]
Let's move this conversation to SkEditor's discord server. You can find invitation link in SkEditor's repository.

**Comment by fsdghyiusfdhiusodf** [comment]
skript*
